INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(18,'Jason', 'Will');
INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(33,'Lilian', 'Mones');
INSERT INTO PERSON_ENTITIES (AGE,NAME,SURNAME)
VALUES(28,'Tom', 'Jones');